name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.4
  - pip=21.1.1
  - pip:
      - wandb==0.10.30
      - git+https://github.com/theyorubayesian/manhattan.git@asiwaju#egg=wandb-utils&subdirectory=components
