name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.1.1
  - requests=2.25.1
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.21
      - git+https://github.com/theyorubayesian/manhattan.git#egg=wandb-utils&subdirectory=project/solution/components
