name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.1.1
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.30
      - git+https://github.com/theyorubayesian/manhattan.git@asiwaju#egg=wandb-utils&subdirectory=components
